### ISSUE TITLE
How to install with Docker

### ISSUE THREAD

**Issue by Eamourinho** [EUdds/Digikey-Inventree-Integration#2]
I have been trying for three weeks to get this running w/ the inventree production docker-compose (https://github.com/inventree/InvenTree/blob/master/docker/production/docker-compose.yml) and have been failing miserably, the plugins page of Inventree indicates that it can't find the 'inventree' package or some other ones.

I'm dying here.

Any chance I could get some idiot-proof instructions on how to get this working w/ the docker-compose?
Where should this plugin reside?
What about it's requirements.txt file?
What URL should I put in the config.ini file? localhost:1337? or localhost:8000? or something else?

**Comment by EUdds** [comment]
I've never used Inventree with docker-compose, but I might try it when I get some free time. Others are welcome to post their experience!

**Comment by Eamourinho** [comment]
I've ended up giving up on inventree and using part-db (https://github.com/Part-DB/Part-DB-server) :D

Easier setup of everything, with simple configuration (just environment variables) for pulling part data from mouser/digikey/octopart.

**Comment by Nudelsalad** [comment]
Is there any progress on this topic as I'm stuck on the same issue?:)

**Comment by EUdds** [comment]
I have yet to test this so your mileage may vary but if you run this plugin outside of your docker container, you can point the URL in the config file to the external port of your server running in your container. Essentially whatever URL and port you use to view the web page I believe you could just point this plugin to that.

If I have some free time this weekend I can give it a shot
