### ISSUE TITLE
query_number no present ? 

### ISSUE THREAD

**Issue by gerisse** [EUdds/digikey-inventree-integration#20]
Hi
i just install yout plugin. Thanks for this work.
But i have this issue : 
 `$ import_digikey_parts.exe -c config.ini 4116R-1-151LF
Traceback (most recent call last):

  File "c:\users\...\appdata\local\programs\python\python39\lib\site-packages\inventree_digikey_integration\__main__.py", line 44, in main
    if len(args.query_number) == 1:
`
an idea for resolve it ?
Bests

**Comment by EUdds** [comment]
Whoops, found a typo, gonna fix and update tests. Fix ETA like an hour

**Comment by EUdds** [comment]
Okay try upgrading the package, `pip install --upgrade  inventree_digikey_integration` and try again. Sorry about that!

**Comment by EUdds** [comment]
If it works again, plz close this. Thanks!

**Comment by gerisse** [comment]
yes. it works !  thanks!
